### ISSUE TITLE
Status are deleted by script

### ISSUE THREAD

**Issue by DrankoLQ** [TheNeonProject/set-profile-status-slack#1]
Something I've seen today: after setting a status in Slack, a few minutes later it was removed. I think that it's caused by the script that remove any status even if there is something on it, without checking if it's 'zona' status or another thing.

Possible solution: before checking if someone is in La Zona, get our current status to not reset it in case is not empty but is not 'zona'

**Comment by javaguirre** [comment]
That's true, it's done that way.

**Comment by javaguirre** [comment]
I'm gonna change the purpose of this project, so I'm gonna close this issue. :-)
